version: "3"
services:
  token_scan:
    image:  annona/token_scan:latest
    container_name: token_scan
    restart: always
    volumes:
      - ./conf:/app/conf
      - ./.env:/app/.env
      - ./upload:/app/upload
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=${LOG_LEVEL}
      - SERVER_GIN_RUNMODE=${SERVER_GIN_RUNMODE}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_URL=${SERVER_URL}
      - SERVER_DB_REDIS_ADDRESS=${SERVER_DB_REDIS_ADDRESS}
      - SERVER_DB_REDIS_PASSWORD=${SERVER_DB_REDIS_PASSWORD}
      - SERVER_DB_TYPE=${SERVER_DB_TYPE}
      - SERVER_DB_HOST=${SERVER_DB_HOST}
      - SERVER_DB_PORT=${SERVER_DB_PORT}
      - SERVER_DB_ADDRESS=${SERVER_DB_ADDRESS}
      - SERVER_DB_USERNAME=${SERVER_DB_USERNAME}
      - SERVER_DB_PASSWORD=${SERVER_DB_PASSWORD}
      - SERVER_DB_NAME=${SERVER_DB_NAME}
      - CORE_API_TOKEN=${CORE_API_TOKEN}
      - CORE_API_URL=${CORE_API_URL}

    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    # depends_on:
    #   - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - umfaka_bot

networks:
  umfaka_bot:
    external: true
